[project]
name = "pgmpy"
version = "1.0.0"
description = "Python Library for Causal and Probabilistic Modeling using Bayesian Networks"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Ankur Ankan", email = "ankurankan@gmail.com" }
]
requires-python = ">=3.10,<3.15"
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Operating System :: Unix",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Bio-Informatics"
]

dependencies = [
  "networkx>=3.0",
  "numpy>=2.0",
  "scipy>=1.10",
  "scikit-learn>=1.2",
  "pandas>=1.5",
  "statsmodels>=0.14.5",
  "tqdm>=4.64",
  "pyparsing>=3.0",
  "joblib>=1.2",
  "opt_einsum>=3.3",
  "scikit-base>=0.12.4",
]

[project.optional-dependencies]
torch = [
  "torch>=2.5",
  "pyro-ppl>=1.9.1",
]
optional = [
  "pgmpy[torch]",
  "daft-pgm>=0.1.4",
  "xgboost>=2.0.3",
  "litellm>=1.61.15",
  "pygraphviz",
]
tests = [
  "xdoctest>=0.11.0",
  "pytest>=3.3.1",
  "pytest-cov",
  "pytest-split",
  "pytest-xdist",
  "coverage>=4.3.4",
  "mock",
  "black",
  "pre-commit",
  "jsonschema",
]
docs = [
  "sphinx>=5.0",
  "nbsphinx",
  "numpydoc",
  "sphinx_rtd_theme",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinxext-opengraph",
  "sphinx_sitemap",
]
all = [
  "pgmpy[optional,tests,docs]",
]

[project.urls]
Documentation = "https://www.pgmpy.org"
Download = "https://pypi.org/project/pgmpy/#files"
Homepage = "https://www.pgmpy.org"
Repository = "https://github.com/pgmpy/pgmpy"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tests"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
pgmpy = [
  "utils/example_models/*.bif.gz",
  "utils/example_models/*.json",
  "utils/example_models/*.txt"
]

[tool.pytest.ini_options]
addopts = "-p no:doctest"
norecursedirs = [".git", "ignore", "build", "__pycache__"]
filterwarnings = ["default"]

[tool.ruff]
line-length = 120
preview = true
exclude = [".git", "examples/*", "docs/source/conf.py", "pgmpy/estimators/__init__.py",
	   "pgmpy/factors/discrete/__init__.py", "pgmpy/identification/__init__.py", "pgmpy/inference/__init__.py",
           "pgmpy/extern/*", "pgmpy/.github/*"]
target-version = "py314"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
  "D",       # pydocstyle
  "DOC",     # pydoclint
  "E",       # https://pypi.org/project/pycodestyle
  "W",       # https://pypi.org/project/pycodestyle
  "F",       # https://pypi.org/project/pyflakes
  "S",       # https://pypi.org/project/flake8-bandit
  "UP",      # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "YTT",     # https://pypi.org/project/flake8-2020/
  "I",       # isort
  "C4",      # https://pypi.org/project/flake8-comprehensions
  "G010",    # Deprecated log warn.
  "PLR1722", # Use sys.exit() instead of exit() and quit().
  "PT014",   # pytest-duplicate-parametrize-test-cases.
  "PT006",   # Checks for the type of parameter names passed to pytest.mark.parametrize.
  "PT007",   # Checks for the type of parameter values passed to pytest.mark.parametrize.
]

ignore = [
  "D100",  # Missing docstring in public module
  "D101",  # Missing docstring in public class
  "D102",  # Missing docstring in public method
  "D103",  # Missing docstring in public function
  "D104",  # Missing docstring in public package
  "D105",  # Missing docstring in magic method
  "S405",  # xml.etree methods are vulnerable to XML attacks
  "S408",  # xml.dom.minidom is vulnerable to XML attacks
  "F822",  # Undefined name in __all__
  "E203",  # Whitespace-before-punctuation.
  "E221",  # Multiple spaces before operator.
  "E222",  # Multiple spaces after operator.
  "E231",  # Missing whitespace after comma.
  "E241",  # Multiple spaces after comma.
  "E712",  # Comparison to True/False using == or !=.
  "E402",  # Module-import-not-at-top-of-file.
  "E731",  # Do not assign a lambda expression, use a def.
  "E741",  # Ambiguous variable name

  "S101",  # Use of `assert` detected.
  "S102",  # Use of excec
  "S105",  # Possible hardcoded password
  "S107",  # Possible hardcoded password
  "S110",  # try-except-pass detected.
  "S113",  # Probable use of httpx call without timeout
  "S202",  # Uses of `tarfile.extractall()`
  "S301",  # pickle and modules that wrap it can be unsafe
  "S307",  # Use of possibly insecure function
  "S310",  # Audit URL open for permitted schemes
  "S311",  # Standard pseudo-random generators not suitable for crypto.
  "S314",  # Using xml to parse untrusted data.
  "S318",  # Using xml minidom to parse untrusted data.
  "S602",  # sub process call with shell=True unsafe
  "S605",  # Starting a process with a shell, possible injection detected

  "C408",  # Unnecessary dict call - rewrite as a literal.
  "C409",  # Unnecessary `list` literal passed to `tuple()` (rewrite as a `tuple` literal)
  "C414",  # Unnecessary `list` call within `sorted()`
  "C416",  # Unnecessary list comprehension - rewrite as a generator
  "C417",  # Unnecessary `map` usage (rewrite using a generator expression)
  "C419",  # Unnecessary list comprehension, some are flagged yet are not

  "UP026", # Replace mock with unittest.mock (external mock has different behavior).
  "UP031", # Use format specifier instead of %
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"





[tool.ruff.lint.per-file-ignores]
"devtools/extension_templates/_causal_discovery.py" = ["D400", "D420"]
"devtools/extension_templates/_metrics.py" = ["D400", "D401", "D420", "DOC501"]
"docs/conf.py" = ["D100"]
"pgmpy/__init__.py" = ["D104"]
"pgmpy/base/ADMG.py" = ["D100", "DOC501"]
"pgmpy/base/AncestralBase.py" = ["D100", "D101", "D205", "D400", "D401", "D420", "DOC202", "DOC501"]
"pgmpy/base/DAG.py" = ["D100", "D102", "D200", "D202", "D205", "D400", "D401", "D409", "D414", "D420", "DOC102", "DOC201", "DOC501"]
"pgmpy/base/MAG.py" = ["D100", "D401", "D420"]
"pgmpy/base/PDAG.py" = ["D100", "D200", "D202", "D205", "D401", "D420", "DOC201", "DOC501"]
"pgmpy/base/SimpleCausalModel.py" = ["D100", "D420"]
"pgmpy/base/UndirectedGraph.py" = ["DOC201", "DOC501"]
"pgmpy/base/__init__.py" = ["D104"]
"pgmpy/base/_base.py" = ["D200", "D205", "D401", "DOC102", "DOC201", "DOC202", "DOC501"]
"pgmpy/base/_mixin_roles.py" = ["D401", "DOC201", "DOC501"]
"pgmpy/causal_discovery/ExpertKnowledge.py" = ["D100", "D205", "D401", "D409", "DOC202", "DOC501"]
"pgmpy/causal_discovery/GES.py" = ["D100", "D200", "D205", "D401", "D420", "DOC201", "DOC501"]
"pgmpy/causal_discovery/HillClimbSearch.py" = ["D100", "D401", "D420", "DOC501"]
"pgmpy/causal_discovery/PC.py" = ["D100", "D202", "D205", "D401", "D420", "DOC501"]
"pgmpy/causal_discovery/__init__.py" = ["D104"]
"pgmpy/causal_discovery/_base.py" = ["D200", "D202", "D205", "D401", "D409", "DOC201", "DOC402", "DOC501"]
"pgmpy/ci_tests/__init__.py" = ["D104"]
"pgmpy/ci_tests/_base.py" = ["D200", "D202", "DOC502"]
"pgmpy/ci_tests/chi_square.py" = ["D100"]
"pgmpy/ci_tests/fisher_z.py" = ["D100", "DOC201"]
"pgmpy/ci_tests/g_sq.py" = ["D100"]
"pgmpy/ci_tests/gcm.py" = ["D100", "DOC201"]
"pgmpy/ci_tests/independence_match.py" = ["D100", "DOC501"]
"pgmpy/ci_tests/log_likelihood.py" = ["D100"]
"pgmpy/ci_tests/modified_log_likelihood.py" = ["D100"]
"pgmpy/ci_tests/pearsonr.py" = ["D100", "D420", "DOC201"]
"pgmpy/ci_tests/pearsonr_equivalence.py" = ["D100", "DOC201"]
"pgmpy/ci_tests/pillai_trace.py" = ["D100", "DOC201"]
"pgmpy/ci_tests/power_divergence.py" = ["D100", "DOC201"]
"pgmpy/datasets/__init__.py" = ["D104"]
"pgmpy/datasets/_base.py" = ["D200", "D205", "D400", "D401", "D404", "DOC201", "DOC501"]
"pgmpy/datasets/abalone.py" = ["D100", "D205"]
"pgmpy/datasets/adult.py" = ["D100", "D205"]
"pgmpy/datasets/airfoil.py" = ["D100", "D101"]
"pgmpy/datasets/algeria.py" = ["D100", "D205"]
"pgmpy/datasets/angrist_krueger.py" = ["D100", "D205"]
"pgmpy/datasets/apple_watch_fitbit.py" = ["D100", "D205"]
"pgmpy/datasets/auto_mpg.py" = ["D100", "D205"]
"pgmpy/datasets/blue_driver.py" = ["D100", "D205"]
"pgmpy/datasets/boston_housing.py" = ["D100", "D205"]
"pgmpy/datasets/cities.py" = ["D100", "D205"]
"pgmpy/datasets/college_plans.py" = ["D100", "D101"]
"pgmpy/datasets/contraceptive_method.py" = ["D100", "D205"]
"pgmpy/datasets/covtype.py" = ["D100", "D101"]
"pgmpy/datasets/credit_approval.py" = ["D100", "D205"]
"pgmpy/datasets/cystic_fibrosis.py" = ["D100", "D101"]
"pgmpy/datasets/depression_coping.py" = ["D100", "D101"]
"pgmpy/datasets/dropouts.py" = ["D100", "D101"]
"pgmpy/datasets/dry_bean.py" = ["D100", "D205"]
"pgmpy/datasets/galton_stature.py" = ["D100", "D205"]
"pgmpy/datasets/goldberg.py" = ["D100", "D101"]
"pgmpy/datasets/hitters.py" = ["D100", "D205"]
"pgmpy/datasets/htru2.py" = ["D100", "D205"]
"pgmpy/datasets/hungary_chickenpox.py" = ["D100", "D205"]
"pgmpy/datasets/iq_brain.py" = ["D100", "D205"]
"pgmpy/datasets/lead.py" = ["D100", "D101"]
"pgmpy/datasets/myocardial_infarction.py" = ["D100", "D205"]
"pgmpy/datasets/pima_diabetes.py" = ["D100", "D205"]
"pgmpy/datasets/pittsburgh_bridges.py" = ["D100", "D205"]
"pgmpy/datasets/residential_building.py" = ["D100", "D205"]
"pgmpy/datasets/sachs.py" = ["D100", "D101"]
"pgmpy/datasets/seoul_bike.py" = ["D100", "D101"]
"pgmpy/datasets/south_german_credit.py" = ["D100", "D205"]
"pgmpy/datasets/spartina.py" = ["D100", "D205"]
"pgmpy/datasets/student_performance.py" = ["D100", "D205"]
"pgmpy/datasets/superconductivity.py" = ["D100", "D205"]
"pgmpy/datasets/tubingen.py" = ["D100", "D205"]
"pgmpy/datasets/uscrime.py" = ["D100", "D205"]
"pgmpy/datasets/wine_quality.py" = ["D100", "D205"]
"pgmpy/datasets/yacht_hydrodynamics.py" = ["D100", "D205"]
"pgmpy/estimators/BaseConstraintEstimator.py" = ["D100", "D205", "D409", "DOC501"]
"pgmpy/estimators/BayesianEstimator.py" = ["D100", "D205", "D401", "DOC501"]
"pgmpy/estimators/CITests.py" = ["D100", "D205", "D301", "D401", "DOC201", "DOC501"]
"pgmpy/estimators/EM.py" = ["D100", "D202", "D205", "D401", "DOC201", "DOC501"]
"pgmpy/estimators/ExhaustiveSearch.py" = ["D100", "D202", "D205", "D301", "D401", "DOC202", "DOC402"]
"pgmpy/estimators/GES.py" = ["D100", "D200", "D202", "D205", "D401", "DOC201"]
"pgmpy/estimators/HillClimbSearch.py" = ["D100", "D202", "D205", "D401", "DOC402", "DOC501"]
"pgmpy/estimators/LinearModel.py" = ["D100", "D102", "D200"]
"pgmpy/estimators/MLE.py" = ["D100", "D202", "D205", "D401", "D409", "DOC501"]
"pgmpy/estimators/MirrorDescentEstimator.py" = ["D100", "D205", "D400", "D401", "D409", "D420", "DOC501"]
"pgmpy/estimators/MmhcEstimator.py" = ["D100", "D202", "D205", "D300", "D401", "DOC201"]
"pgmpy/estimators/PC.py" = ["D100", "D202", "D205", "DOC501"]
"pgmpy/estimators/SEMEstimator.py" = ["D100", "D200", "D205", "D401", "DOC201", "DOC501"]
"pgmpy/estimators/ScoreCache.py" = ["D100", "D102", "D205"]
"pgmpy/estimators/StructureScore.py" = ["D100", "D102", "D103", "D202", "D205", "D401", "D420", "DOC502"]
"pgmpy/estimators/TreeSearch.py" = ["D100", "D200", "D205", "D400", "D401", "DOC201", "DOC501"]
"pgmpy/estimators/base.py" = ["D100", "D102", "D202", "D205", "D300", "D401", "DOC201", "DOC501"]
"pgmpy/estimators/expert.py" = ["D100", "D101", "DOC201"]
"pgmpy/example_models/__init__.py" = ["D104"]
"pgmpy/example_models/_base.py" = ["D200", "D205", "D401", "DOC201", "DOC501"]
"pgmpy/example_models/bnlearn/__init__.py" = ["D104"]
"pgmpy/example_models/bnlearn/alarm.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/andes.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/arth150.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/asia.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/barley.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/cancer.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/child.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/diabetes.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/earthquake.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/ecoli70.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/hailfinder.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/hepar2.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/insurance.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/link.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/magic_irri.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/magic_niab.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/mildew.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/munin.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/munin1.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/munin2.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/munin3.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/munin4.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/pathfinder.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/pigs.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/sachs.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/survey.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/water.py" = ["D100", "D205"]
"pgmpy/example_models/bnlearn/win95pts.py" = ["D100", "D205"]
"pgmpy/example_models/bnrep/APSsystem.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/BOPfailure1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/BOPfailure2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/BOPfailure3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/GDIpathway1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/GDIpathway2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/__init__.py" = ["D104"]
"pgmpy/example_models/bnrep/accidents.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/adhd.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/adversarialbehavior.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/aerialvehicles.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/agropastoral1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/agropastoral2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/agropastoral3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/agropastoral4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/agropastoral5.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/aircrash.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/airegulation1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/airegulation2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/airegulation3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algal1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algal2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algalactivity1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algalactivity2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algorithms1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algorithms2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algorithms3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/algorithms4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/arcticwaters.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/argument.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/asia.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/augmenting.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/bank.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/bankruptcy.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/beam1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/beam2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/beatles.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/blacksea.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/blockchain.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/building.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/bullet.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/burglar.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/cachexia1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/cachexia2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/cardiovascular.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/case.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/catchment.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/charleston.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/chds.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/cng.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/compaction.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/conasense.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete5.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete6.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/concrete7.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/consequenceCovid.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/constructionproductivity.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/coral1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/coral2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/coral3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/coral4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/coral5.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/corical.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/corrosion.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/corticosteroid.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covid1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covid2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covid3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covidfear.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covidrisk.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/covidtech.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/crimescene.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/criminal1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/criminal2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/criminal3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/criminal4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/crypto.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/curacao1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/curacao2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/curacao3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/curacao4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/curacao5.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/diabetes.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/diagnosis.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/dioxins.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/disputed1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/disputed2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/disputed3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/disputed4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/dragline.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/drainage.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/dustexplosion.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/earthquake.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/ecosystem.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/electricvehicle.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/electrolysis.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/emergency.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/engines.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/enrollment.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/estuary.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/ets.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/expenditure.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fingermarks1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fingermarks2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fire.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/firealarm.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/firerisk.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/flood.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fluids1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fluids2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fluids3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/foodallergy1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/foodallergy2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/foodallergy3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/foodsecurity.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/forest.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/fundraising.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/gasexplosion.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/gasifier.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/gonorrhoeae.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/greencredit.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/grounding.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/humanitarian.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/hydraulicsystem.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/income.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/intensification.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/intentionalattacks.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/inverters.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/knowledge.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/kosterhavet.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/lawschool.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/lexical.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/lidar.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/liquefaction.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/liquidity.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/lithium.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/macrophytes.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/medicaltest.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/megacities.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/metal.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/moodstate.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/mountaingoat.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/nanomaterials1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/nanomaterials2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/navigation.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/nuclearwaste.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/nuisancegrowth.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/oildepot.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/onlinerisk.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/orbital.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/oxygen.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/perioperative.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/permaBN.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/phdarticles.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/pilot.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/pneumonia.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/polymorphic.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/poultry.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/project.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/projectmanagement.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/propellant.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/rainstorm.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/rainwater.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/realestate1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/realestate2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/realestate3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/redmeat.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/resilience.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/ricci.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/rockburst.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/rockquality.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/ropesegment.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/safespeeds.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/sallyclark.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/salmonella1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/salmonella2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/seismic.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/shipping.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/simulation.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/softwarelogs1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/softwarelogs2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/softwarelogs3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/softwarelogs4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soil.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soillead.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soilliquefaction1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soilliquefaction2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soilliquefaction3.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/soilliquefaction4.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/stocks.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/student1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/student2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/suffocation.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/tastingtea.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/tbm.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/theft1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/theft2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/titanic.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/trajectories.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/transport.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/tubercolosis.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/turbine1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/turbine2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/twinframework.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/urinary.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/vaccine.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/vessel1.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/vessel2.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/volleyball.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/waterlead.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/wheat.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/windturbine.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/witness.py" = ["D100", "D101"]
"pgmpy/example_models/bnrep/yangtze.py" = ["D100", "D101"]
"pgmpy/example_models/dagitty/__init__.py" = ["D104"]
"pgmpy/example_models/dagitty/acid_1996.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/confounding.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/didelez_2010.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/kampen_2014.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/m_bias.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/mediator.py" = ["D100", "D200"]
"pgmpy/example_models/dagitty/paths.py" = ["D100", "D200"]
"pgmpy/example_models/dagitty/polzer_2012.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/schipf_2010.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/sebastiani_2005.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/shrier_2008.py" = ["D100", "D205"]
"pgmpy/example_models/dagitty/thoemmes_2013.py" = ["D100", "D205"]
"pgmpy/factors/FactorDict.py" = ["D100", "D101", "D102", "D105", "DOC501"]
"pgmpy/factors/FactorSet.py" = ["D100", "D105", "D400", "D401", "D409", "DOC102", "DOC201", "DOC501"]
"pgmpy/factors/__init__.py" = ["D104"]
"pgmpy/factors/base.py" = ["D100", "D102", "D200", "D205", "D401", "DOC501"]
"pgmpy/factors/continuous/LinearGaussianCPD.py" = ["D100", "D105", "D205", "D400", "D401", "D420"]
"pgmpy/factors/continuous/__init__.py" = ["D104"]
"pgmpy/factors/discrete/CPD.py" = ["D105", "D200", "D205", "D400", "D401", "D412", "DOC201", "DOC501"]
"pgmpy/factors/discrete/DiscreteFactor.py" = ["D100", "D105", "D200", "D202", "D205", "D401", "DOC201", "DOC202", "DOC501"]
"pgmpy/factors/discrete/JointProbabilityDistribution.py" = ["D100", "D102", "D105", "D200", "D205", "D400", "D401", "D409", "DOC102", "DOC201", "DOC501"]
"pgmpy/factors/discrete/NoisyOR.py" = ["D100"]
"pgmpy/factors/hybrid/FunctionalCPD.py" = ["D100", "D105", "D401", "D412", "DOC501"]
"pgmpy/factors/hybrid/__init__.py" = ["D104"]
"pgmpy/global_vars.py" = ["D100", "D101", "D102", "D200", "D401", "DOC201", "DOC501"]
"pgmpy/identification/adjustment.py" = ["D100", "D401", "D420", "DOC201"]
"pgmpy/identification/base.py" = ["D100", "D400", "DOC201"]
"pgmpy/identification/frontdoor.py" = ["D100", "D419"]
"pgmpy/independencies/Independencies.py" = ["D100", "D102", "D105", "D200", "D205", "D300", "D400", "D401", "D412", "DOC201", "DOC501"]
"pgmpy/independencies/__init__.py" = ["D104"]
"pgmpy/inference/ApproxInference.py" = ["D100", "D200", "D205", "D401", "DOC201"]
"pgmpy/inference/CausalInference.py" = ["D100", "D102", "D105", "D205", "D301", "D400", "D401", "D404", "D412", "D420", "DOC201", "DOC501"]
"pgmpy/inference/EliminationOrder.py" = ["D100", "D101", "D205", "D400", "D401", "DOC201"]
"pgmpy/inference/ExactInference.py" = ["D100", "D101", "D200", "D202", "D205", "D400", "D401", "D404", "D420", "DOC102", "DOC201", "DOC501"]
"pgmpy/inference/LinearModel.py" = ["D100", "D102", "D200"]
"pgmpy/inference/base.py" = ["D100", "D205", "D400", "D401", "D420", "DOC201", "DOC202", "DOC501"]
"pgmpy/inference/dbn_inference.py" = ["D100", "D202", "D205", "D401", "D420", "DOC102", "DOC201"]
"pgmpy/inference/mplp.py" = ["D100", "D102", "D200", "D202", "D205", "D400", "D401", "D404", "D409", "DOC102", "DOC201"]
"pgmpy/metrics/__init__.py" = ["D104"]
"pgmpy/metrics/_base.py" = ["D200", "DOC201", "DOC501", "DOC502"]
"pgmpy/metrics/adjacency_cm.py" = ["D100", "D420", "DOC201"]
"pgmpy/metrics/correlation_score.py" = ["D100", "D205"]
"pgmpy/metrics/fisher_c.py" = ["D100", "D205"]
"pgmpy/metrics/implied_cis.py" = ["D100"]
"pgmpy/metrics/orientation_cm.py" = ["D100", "D202", "D420", "DOC201"]
"pgmpy/metrics/shd.py" = ["D100"]
"pgmpy/metrics/structure_score.py" = ["D100", "D205"]
"pgmpy/models/BayesianNetwork.py" = ["D100", "D101"]
"pgmpy/models/ClusterGraph.py" = ["D100", "D205", "D400", "D401", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/DiscreteBayesianNetwork.py" = ["D100", "D102", "D202", "D205", "D400", "D401", "D420", "DOC102", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/DiscreteMarkovNetwork.py" = ["D100", "D205", "D400", "D401", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/DynamicBayesianNetwork.py" = ["D100", "D102", "D105", "D200", "D202", "D205", "D400", "D401", "D404", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/FactorGraph.py" = ["D100", "D205", "D400", "D401", "DOC201", "DOC501"]
"pgmpy/models/FunctionalBayesianNetwork.py" = ["D100", "D205", "D400", "D401", "DOC501"]
"pgmpy/models/JunctionTree.py" = ["D100", "D205", "D401", "DOC501"]
"pgmpy/models/LinearGaussianBayesianNetwork.py" = ["D100", "D200", "D202", "D205", "D400", "D401", "D410", "D411", "DOC201", "DOC501"]
"pgmpy/models/MarkovChain.py" = ["D100", "D200", "D205", "D400", "D401", "D412", "DOC201", "DOC202", "DOC402", "DOC501"]
"pgmpy/models/MarkovNetwork.py" = ["D100", "D101"]
"pgmpy/models/NaiveBayes.py" = ["D100", "D202", "D205", "D401", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/SEM.py" = ["D100", "D102", "D200", "D202", "D205", "D400", "D401", "D404", "D414", "D420", "DOC102", "DOC201", "DOC202", "DOC501"]
"pgmpy/models/__init__.py" = ["D104"]
"pgmpy/prediction/DoubleMLRegressor.py" = ["D100", "D401", "D420", "DOC501"]
"pgmpy/prediction/NaiveAdjustmentRegressor.py" = ["D200", "D202", "DOC201", "DOC501"]
"pgmpy/prediction/NaiveIVRegressor.py" = ["D100", "D102", "D202", "D205", "D401", "D404", "D420", "DOC501"]
"pgmpy/prediction/__init__.py" = ["D104"]
"pgmpy/prediction/_base.py" = ["D202", "D205", "DOC501"]
"pgmpy/readwrite/BIF.py" = ["D100", "D102", "D200", "D400", "D401", "D409", "DOC102", "DOC201"]
"pgmpy/readwrite/NET.py" = ["D100", "D102", "D200", "D202", "D205", "D400", "D401", "D409", "DOC102", "DOC201", "DOC501"]
"pgmpy/readwrite/PomdpX.py" = ["D100", "D200", "D205", "D400", "D401", "D403", "D404", "D409", "D412", "DOC102", "DOC201"]
"pgmpy/readwrite/UAI.py" = ["D100", "D102", "D200", "D205", "D400", "D401", "D407", "DOC201", "DOC501"]
"pgmpy/readwrite/XDSL.py" = ["D100", "D102", "D205", "D400", "D401", "D409", "D414", "DOC201", "DOC501"]
"pgmpy/readwrite/XMLBIF.py" = ["D100", "D102", "D200", "D205", "D400", "D401", "D409", "DOC201"]
"pgmpy/readwrite/XMLBeliefNetwork.py" = ["D100", "D102", "D200", "D400", "D401", "DOC102", "DOC201"]
"pgmpy/readwrite/__init__.py" = ["D104"]
"pgmpy/sampling/Sampling.py" = ["D100", "D202", "D205", "D400", "D401", "DOC202", "DOC402"]
"pgmpy/sampling/__init__.py" = ["D104"]
"pgmpy/sampling/base.py" = ["D100", "D200", "D205", "D400", "D401", "DOC201"]
"pgmpy/tests/__init__.py" = ["D104"]
"pgmpy/tests/help_functions.py" = ["D100", "D103"]
"pgmpy/tests/test_base/__init__.py" = ["D104"]
"pgmpy/tests/test_base/test_ADMG.py" = ["D100", "D102", "D205"]
"pgmpy/tests/test_base/test_AncestralBase.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_base/test_DAG.py" = ["D100", "D101", "D102", "D400"]
"pgmpy/tests/test_base/test_MAG.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_base/test_PDAG.py" = ["D100", "D101", "D102", "D205"]
"pgmpy/tests/test_base/test_SimpleCausalModel.py" = ["D100", "D103"]
"pgmpy/tests/test_base/test_UndirectedGraph.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_base/test_base.py" = ["D100", "D101", "D102", "D205", "D400", "D401", "D403", "DOC201"]
"pgmpy/tests/test_base/test_causal_graph.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_base/test_mixin_roles.py" = ["D100", "D103"]
"pgmpy/tests/test_causal_discovery/test_GES.py" = ["D102", "D103", "D200"]
"pgmpy/tests/test_causal_discovery/test_HillClimbSearch.py" = ["D103", "D200"]
"pgmpy/tests/test_causal_discovery/test_PC.py" = ["D100", "D103", "D205", "D400", "D401", "DOC201"]
"pgmpy/tests/test_ci_tests/__init__.py" = ["D104"]
"pgmpy/tests/test_ci_tests/test_base.py" = ["D100", "D103"]
"pgmpy/tests/test_ci_tests/test_chi_square.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_fisher_z.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_g_sq.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_gcm.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_log_likelihood.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_modified_log_likelihood.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_pearsonr.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_pearsonr_equivalence.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_ci_tests/test_pillai_trace.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_datasets/test_datasets.py" = ["D100", "D103"]
"pgmpy/tests/test_devtools/test_lgbn_schema.py" = ["D100"]
"pgmpy/tests/test_estimators/__init__.py" = ["D104"]
"pgmpy/tests/test_estimators/test_BaseEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_BayesianEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_CITests.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_estimators/test_EM.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_estimators/test_ExhaustiveSearch.py" = ["D100", "D103", "D200"]
"pgmpy/tests/test_estimators/test_GES.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_HillClimbSearch.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_estimators/test_MarginalEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_MaximumLikelihoodEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_MirrorDescentEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_MmhcEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_PC.py" = ["D100", "D103", "D205", "D400", "D401", "DOC201"]
"pgmpy/tests/test_estimators/test_ParameterEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_SEMEstimator.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_ScoreCache.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_StructureScore.py" = ["D100", "D101", "D102", "D103", "D400", "D401", "DOC201"]
"pgmpy/tests/test_estimators/test_TreeSearch.py" = ["D100", "D103"]
"pgmpy/tests/test_estimators/test_expert.py" = ["D100", "D101", "D102", "D103", "DOC201"]
"pgmpy/tests/test_example_models/test_example_models.py" = ["D100", "D103"]
"pgmpy/tests/test_factors/__init__.py" = ["D104"]
"pgmpy/tests/test_factors/test_FactorDict.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_factors/test_FactorSet.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_factors/test_continuous/__init__.py" = ["D104"]
"pgmpy/tests/test_factors/test_continuous/test_Linear_Gaussian_CPD.py" = ["D100", "D103"]
"pgmpy/tests/test_factors/test_discrete/__init__.py" = ["D104"]
"pgmpy/tests/test_factors/test_discrete/test_Factor.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_factors/test_discrete/test_FactorTorch.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_factors/test_discrete/test_NoisyOR.py" = ["D100", "D103"]
"pgmpy/tests/test_factors/test_hybrid/__init__.py" = ["D104"]
"pgmpy/tests/test_factors/test_hybrid/test_Functional_CPD.py" = ["D100", "D103", "D200"]
"pgmpy/tests/test_global_vars.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_identification/test_adjustment.py" = ["D100", "D102", "D103", "D205"]
"pgmpy/tests/test_identification/test_base.py" = ["D100", "D101", "D102", "D103", "D205"]
"pgmpy/tests/test_identification/test_frontdoor.py" = ["D100", "D103"]
"pgmpy/tests/test_independencies/__init__.py" = ["D104"]
"pgmpy/tests/test_independencies/test_Independencies.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_inference/__init__.py" = ["D104"]
"pgmpy/tests/test_inference/test_ApproxInference.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_inference/test_CausalInference.py" = ["D100", "D101", "D102", "D205"]
"pgmpy/tests/test_inference/test_ExactInference.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_inference/test_ExactInferenceTorch.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_inference/test_Inference.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_inference/test_dbn_inference.py" = ["D100", "D101", "D102", "D205"]
"pgmpy/tests/test_inference/test_elimination_order.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_inference/test_mplp.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_metrics/__init__.py" = ["D104"]
"pgmpy/tests/test_metrics/test_adjacency_confusion_matrix.py" = ["D100", "D103"]
"pgmpy/tests/test_metrics/test_correlation_score.py" = ["D100", "D103"]
"pgmpy/tests/test_metrics/test_fisher_c.py" = ["D100", "D103", "DOC201"]
"pgmpy/tests/test_metrics/test_implied_cis.py" = ["D100", "D103"]
"pgmpy/tests/test_metrics/test_orientation_confusion_matrix.py" = ["D100", "D103"]
"pgmpy/tests/test_metrics/test_shd.py" = ["D100", "D103"]
"pgmpy/tests/test_metrics/test_structure_score.py" = ["D100", "D101", "D102", "D103"]
"pgmpy/tests/test_models/__init__.py" = ["D104"]
"pgmpy/tests/test_models/test_ClusterGraph.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_DiscreteBayesianNetwork.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_DiscreteMarkovNetwork.py" = ["D100", "D101", "D102", "D200", "D205"]
"pgmpy/tests/test_models/test_DynamicBayesianNetwork.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_FactorGraph.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_FunctionalBayesianNetwork.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_JunctionTree.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_LinearGaussianBayesianNetwork.py" = ["D100", "D101", "D102", "D400"]
"pgmpy/tests/test_models/test_MarkovChain.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_NaiveBayes.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_models/test_SEM.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_prediction/test_DoubleMLRegressor.py" = ["D100", "D103", "D202", "DOC201"]
"pgmpy/tests/test_prediction/test_NaiveAdjustmentRegressor.py" = ["D200", "D202", "DOC201"]
"pgmpy/tests/test_prediction/test_NaiveIVRegressor.py" = ["D100", "D103", "D202", "DOC201"]
"pgmpy/tests/test_readwrite/__init__.py" = ["D104"]
"pgmpy/tests/test_readwrite/test_BIF.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_NET.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_PomdpX.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_UAI.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_XMLBIF.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_XMLBeliefNetwork.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_readwrite/test_xdsl.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_sampling/__init__.py" = ["D104"]
"pgmpy/tests/test_sampling/test_BayesianModelSampling.py" = ["D100", "D103"]
"pgmpy/tests/test_sampling/test_GibbsSampling.py" = ["D100", "D103"]
"pgmpy/tests/test_utils/test_optimizer.py" = ["D100", "D101", "D102", "D205", "D400"]
"pgmpy/tests/test_utils/test_state_name.py" = ["D100", "D101", "D102"]
"pgmpy/tests/test_utils/test_utils.py" = ["D100", "D101", "D102"]
"pgmpy/utils/__init__.py" = ["D104"]
"pgmpy/utils/check_functions.py" = ["D200", "D400", "D401", "DOC201", "DOC501"]
"pgmpy/utils/compat_fns.py" = ["D103"]
"pgmpy/utils/mathext.py" = ["D100", "D205", "D401", "DOC102", "DOC201", "DOC501"]
"pgmpy/utils/optimizer.py" = ["D100", "D401", "D414"]
"pgmpy/utils/parser.py" = ["D100", "D103"]
"pgmpy/utils/sets.py" = ["D100", "D205", "D400", "D409", "DOC501"]
"pgmpy/utils/state_name.py" = ["D100", "D200", "D205", "D400", "D401", "D404", "DOC201", "DOC501"]
"pgmpy/utils/utils.py" = ["D100", "D200", "D202", "D205", "D401", "D412", "D420", "DOC501"]
"tmp.py" = ["D100", "D103"]
"tmp2.py" = ["D100", "D103"]
"tmp3.py" = ["D100", "D103"]
"tmp4.py" = ["D100"]
"tmp5.py" = ["D100"]
"tmp6.py" = ["D100"]
"tmp7.py" = ["D100"]
